[package]
name = "llvm"
version = "0.1.0"
authors = ["Evgeny Ukhanov <mrlsd@ya.ru>"]
edition = "2018"

[dependencies]
llvm-sys = "100.2.0"

[dependencies.inkwell]
git = "https://github.com/TheDan64/inkwell"
rev = "7b2e20f"
features = ["llvm10-0"]
 